os: linux
sudo: required
language: python
cache: pip

python:
  - "3.5"
  - "3.6"

before_install:
- sudo docker run -d -p 27017:27017 mongo
- cd Server

install:
  - pip3 install -r requirements.txt

notifications:
  email: false
