os: linux
sudo: required
language: python
cache: pip

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo docker run -d -p 27017:27017 mongo

install:
  - pip3 install -r requirements.txt

before_script:
  - cd Server

script: 
  - pytest

notifications:
  email: false
